# Microplane theory - Energy dissipation study - N-T projection - compression

- Notebook dedicated to the study of the energy dissipation macro-micro discrepancy detected during ComPlas Paper.

- For simplicity no linear solver is going to be used. 

- Three different homogenization approaches are employed.

# Constitutive equations

- The constitutive equations have been simplified, ir order to rule out possible sources of error. 
- Ideal elasto-plastic behaviour is going to be considered.  

**Normal direction**

\begin{align}\label{eq:helmholtz_free_energy_N} 
\rho \psi_\mathrm{N}^{\mathrm{mic}} &= \frac{1}{2} E_\mathrm{N} (\varepsilon_\mathrm{N} - \varepsilon^\mathrm{p}_\mathrm{N})^2 ,\end{align}

with $E_\mathrm{N}$ given as 

\begin{equation}
\label{eq:E_N_from_triaxial}
    E_\mathrm{N} = \dfrac{E}{(1-2\nu)}.
\end{equation}

Normal stresses are obtained as

\begin{equation}
\sigma_\mathrm{N} = \dfrac{\partial \rho \psi_\mathrm{N}}{\partial \varepsilon_\mathrm{N} } = E_\mathrm{N}  (\varepsilon_\mathrm{N} - \varepsilon^{\mathrm{P}}_\mathrm{N}).
\end{equation}

The function defining the plastic threshold in compression is  defined as follows
\begin{align}\label{eq:threshold_plasticity_N}
&f_\mathrm{N}^\mathrm{p} = |\sigma_\mathrm{N}| - \sigma_\mathrm{N}^0  \leq 0,
\end{align} 

The evolution equation is defined as
\begin{align}\dot{\varepsilon}_\mathrm{N}^{\mathrm{p}} = \dot{\varepsilon}_\mathrm{N} \end{align}.

Similarly for **the tangential direction**

\begin{align} \label{eq:helmholtz_free_enrg_T} 
\rho \psi_\mathrm{T}^{\mathrm{mic}} &= \frac{1}{2} E_\mathrm{T} (\boldsymbol{\varepsilon_\mathrm{T}} - \boldsymbol{\varepsilon^{\pi}_\mathrm{T}}) \cdot (\boldsymbol{\varepsilon_\mathrm{T}} - \boldsymbol{\varepsilon^{\pi}_\mathrm{T}}), 
\end{align}

\begin{equation}
\label{eq:E_T_from_triaxial}
    E_\mathrm{T} = \dfrac{E(1-4\nu)}{(1+\nu)(1-2\nu)},
\end{equation}

\begin{align}
&\boldsymbol{\sigma_\mathrm{T}}= \dfrac{\partial \rho \psi_\mathrm{T}}{\partial \boldsymbol{\varepsilon_\mathrm{T}} }=  E_\mathrm{T}  (\boldsymbol{\varepsilon_\mathrm{T}} - \boldsymbol{\varepsilon^{\pi}_\mathrm{T}})
\end{align}

\begin{equation}
f_\mathrm{T} = ||{\boldsymbol{\sigma_\mathrm{T}}}||- \sigma_\mathrm{T}^0  \leq 0,
\end{equation}

\begin{align}
&\boldsymbol{\dot{\varepsilon}_\mathrm{T}^{\pi}} = \boldsymbol{\dot{\varepsilon}_\mathrm{T}}\end{align}

# Homogenization concepts

- The studied cases make use of the kinematic constraint 
- Once that the state variables at the microplane level are obtained they have to be integrated 
- Two studies are going to be conducted. 
- The first one will obtain the macroscopic stress tensor by numerical integration of the microplane contributions. For simplicity it will be named **PVW approach**
- The second one considers the macroscopic elastic stiffner tensor and the macrospcopic plastic tensor. This will be named **EEQ approach**
- The **stress-strain** response and **total and plastic work** for the microplanes and macroscopic tensor will be obtained

## PVW approach

Macroscopic tensor $\sigma$ is obtained as follows
\begin{equation}
\sigma_{ij} = \frac{3}{2\pi} \int_{\Omega} \sigma_{\mathrm{N}} n_i n_j \,\mathrm{d}\Omega + \frac{3}{2\pi} \int_{\Omega} \frac{\sigma_{\mathrm{T}_r}}{2} \,
\left(n_i \delta_{rj} + n_j \delta_{ri}\right) \, \mathrm{d}\Omega.
\label{eq:sigma_ij}
\end{equation}


## EEQ approach

Macroscopic tensor $\sigma$ is obtained as follows
\begin{equation}
\label{eq:corrector_predictor}
\boldsymbol{\sigma} = \boldsymbol{C}^{\mathrm{e}}:(\boldsymbol{\varepsilon} - \boldsymbol{\varepsilon}^\mathrm{p}). 
\end{equation}

Macroscopic plastic tensor is obtained as: 
\begin{align} \label{eq:plastic_strain_tensor} 
\varepsilon^{p}_{ij} &= \frac{3}{2 \pi} \int_{\Omega}  \varepsilon^{p,\mathrm{mic}}_\mathrm{N}  n_i n_j  d \Omega + \frac{3}{2 \pi} \int_{\Omega} \frac{\varepsilon^{\pi,\mathrm{mic}}_{\mathrm{T}r}}{2} (n_i  \delta_{rj} + n_j \delta_{ri}) d \Omega.
\end{align}

# Energy evaluation

## Macroscopic level

\begin{equation} W_{\mathrm{Total}} = W_{\mathrm{Elastic}} + W_{\mathrm{Plastic}} \end{equation}

\begin{equation} W_{\mathrm{Total}} = \sum_{step=0}^{step=n} \sigma_{ij} : \Delta \varepsilon_{ij}  \end{equation}

\begin{equation} W_{\mathrm{Elastic}} = \sum_{step=0}^{step=n} \sigma_{ij} : \Delta (\varepsilon_{ij} - \varepsilon^p_{ij})  \end{equation}

\begin{equation} W_{\mathrm{Plastic}} = \sum_{step=0}^{step=n} \sigma_{ij} : \Delta \varepsilon^p_{ij}  \end{equation}

## Microplane level

\begin{equation} W_{\mathrm{Total}} = \sum_{step=0}^{step=n}(\sum_{mic} w^{\mathrm{mic}}(\sigma^{\mathrm{mic}}_{\mathrm{N}} \Delta \varepsilon^{\mathrm{mic}}_{\mathrm{N}} + \sigma^{\mathrm{mic}}_{\mathrm{T}} \cdot \Delta \varepsilon^{\mathrm{mic}}_{\mathrm{T}}))   \end{equation}

\begin{equation} W_{\mathrm{Elastic}} = \sum_{step=0}^{step=n}(\sum_{mic} w^{\mathrm{mic}}(\sigma^{\mathrm{mic}}_{\mathrm{N}} \Delta (\varepsilon^{\mathrm{mic}}_{\mathrm{N}} - \varepsilon^{p,\mathrm{mic}}_{\mathrm{N}}) + \sigma^{\mathrm{mic}}_{\mathrm{T}} \cdot \Delta (\varepsilon^{\mathrm{mic}}_{\mathrm{T}} - \varepsilon^{\pi,\mathrm{mic}}_{\mathrm{T}})))   \end{equation}

\begin{equation} W_{\mathrm{Plastic}} = \sum_{step=0}^{step=n}(\sum_{mic} w^{\mathrm{mic}}(\sigma^{\mathrm{mic}}_{\mathrm{N}} \Delta \varepsilon^{p,\mathrm{mic}}_{\mathrm{N}} + \sigma^{\mathrm{mic}}_{\mathrm{T}} \cdot \Delta \varepsilon^{\pi,\mathrm{mic}}_{\mathrm{T}}))   \end{equation}

# Implementation

In [1]:
# import matplotlib.pyplot as plt
import numpy as np   
from traits.api import Constant, HasTraits, Property, cached_property
import traits.api as tr
import copy
# import matplotlib


In [2]:
class MATS3DMplNTSimp(HasTraits):
    concrete_type = tr.Int

    tau_pi_bar = tr.Float(5.,
                          label="Tau_bar",
                          desc="Reversibility limit",
                          enter_set=True,
                          auto_set=False)


    sigma_0 = tr.Float(5.,
                       label="sigma_0",
                       desc="Yielding stress",
                       enter_set=True,
                       auto_set=False)

    # -------------------------------------------------------------------------
    # Cached elasticity tensors
    # -------------------------------------------------------------------------

    E = tr.Float(35e+3,
                 label="E",
                 desc="Young's Modulus",
                 auto_set=False,
                 input=True)

    nu = tr.Float(0.2,
                  label='nu',
                  desc="Poison ratio",
                  auto_set=False,
                  input=True)

    # --------------------------------------------------------------
    # microplane constitutive law (normal behavior CP + TD)
    # --------------------------------------------------------------
    def get_normal_law(self, eps_N_Emn, eps_N_p_Emn, eps_N_aux):

        E_N = self.E / (1.0 - 2.0 * self.nu)
        sigma_trial = E_N * (eps_N_Emn - eps_N_p_Emn)
        h = (self.sigma_0)

        f_trial = (abs(sigma_trial) - h) 
        # threshold plasticity

        thres_1 = f_trial > 1e-6

        eps_N_p_Emn = eps_N_p_Emn + (eps_N_Emn - eps_N_aux) * thres_1 

        sigma_N_Emn =  E_N * (eps_N_Emn - eps_N_p_Emn)

        return eps_N_p_Emn, sigma_N_Emn

    # -------------------------------------------------------------------------
    # microplane constitutive law (Tangential CSD)-(Pressure sensitive cumulative damage)
    # -------------------------------------------------------------------------
    def get_tangential_law(self, eps_T_Emna, eps_T_pi_Emna, eps_T_aux):

        E_T = self.E * (1.0 - 4 * self.nu) / \
              ((1.0 + self.nu) * (1.0 - 2 * self.nu))

        # thermo forces

        sig_pi_trial = E_T * (eps_T_Emna - eps_T_pi_Emna)

        norm_1 = np.sqrt(
            np.einsum(
                '...na,...na->...n',
                (sig_pi_trial), (sig_pi_trial))
        )

        # threshold

        f = norm_1 - self.tau_pi_bar    

        plas_1 = f > 1e-6

        eps_T_pi_Emna[...,0] = eps_T_pi_Emna[...,0] + (eps_T_Emna[...,0] - eps_T_aux[...,0]) * plas_1
        eps_T_pi_Emna[...,1] = eps_T_pi_Emna[...,1] + (eps_T_Emna[...,1] - eps_T_aux[...,1]) * plas_1
        eps_T_pi_Emna[...,2] = eps_T_pi_Emna[...,2] + (eps_T_Emna[...,2] - eps_T_aux[...,2]) * plas_1
        
        sigma_T_Emna = E_T * (eps_T_Emna - eps_T_pi_Emna)

        return eps_T_pi_Emna, sigma_T_Emna



    # -------------------------------------------------------------------------
    # MICROPLANE-Kinematic constraints
    # -------------------------------------------------------------------------
    # get the operator of the microplane normals
    _MPNN = tr.Property(depends_on='n_mp')

    @tr.cached_property
    def _get__MPNN(self):
        MPNN_nij = np.einsum('ni,nj->nij', self._MPN, self._MPN)
        return MPNN_nij

    # get the third order tangential tensor (operator) for each microplane
    _MPTT = tr.Property(depends_on='n_mp')

    @tr.cached_property
    def _get__MPTT(self):
        delta = np.identity(3)
        MPTT_nijr = 0.5 * (
                np.einsum('ni,jr -> nijr', self._MPN, delta) +
                np.einsum('nj,ir -> njir', self._MPN, delta) - 2 *
                np.einsum('ni,nj,nr -> nijr', self._MPN, self._MPN, self._MPN)
        )
        return MPTT_nijr

    def _get_e_N_Emn(self, eps_Emab):
        # get the normal strain array for each microplane
        return np.einsum('nij,...ij->...n', self._MPNN, eps_Emab)

    def _get_e_T_Emnar(self, eps_Emab):
        # get the tangential strain vector array for each microplane
        MPTT_ijr = self._get__MPTT()
        return np.einsum('nija,...ij->...na', MPTT_ijr, eps_Emab)

    # --------------------------------------------------------
    # return the state variables (Damage , inelastic strains)
    # --------------------------------------------------------
    def _x_get_state_variables(self, eps_Emab,
                             int_var, int_var_accepted):

        eps_N_Emn = self._get_e_N_Emn(eps_Emab)
        eps_T_Emna = self._get_e_T_Emnar(eps_Emab)
    
        eps_N_aux = copy.deepcopy(int_var_accepted[:, 1])
        eps_N_p_Emn = copy.deepcopy(int_var_accepted[:, 0])
        eps_T_pi_Emna = copy.deepcopy(int_var_accepted[:, 3:6])
        eps_T_aux = copy.deepcopy(int_var_accepted[:, 6:9])        
                           
        eps_N_p_Emn, sigma_N_Emn = copy.deepcopy(self.get_normal_law(
            eps_N_Emn, eps_N_p_Emn, eps_N_aux))

        eps_T_pi_Emna, sigma_T_Emna = copy.deepcopy(self.get_tangential_law(
            eps_T_Emna, eps_T_pi_Emna, eps_T_aux))

        int_var[:, 0] = copy.deepcopy(eps_N_p_Emn)
        int_var[:, 1] = copy.deepcopy(eps_N_Emn)
        int_var[:, 2] = copy.deepcopy(sigma_N_Emn)

        int_var[:, 3:6] = copy.deepcopy(eps_T_pi_Emna)
        int_var[:, 6:9] = copy.deepcopy(eps_T_Emna)
        int_var[:, 9:12] = copy.deepcopy(sigma_T_Emna)
                           
        return int_var
    
    def get_corr_pred_PVW(self, eps_Emab, int_var_accepted): 

        # Corrector predictor computation.

        e_N_arr = self._get_e_N_Emn(eps_Emab)
        e_T_vct_arr = self._get_e_T_Emnar(eps_Emab)
        
        eps_N_aux = copy.deepcopy(int_var_accepted[:, 1])
        eps_N_p_Emn_aux = copy.deepcopy(int_var_accepted[:, 0])
        eps_T_pi_Emna_aux = copy.deepcopy(int_var_accepted[:, 3:6])
        eps_T_aux = copy.deepcopy(int_var_accepted[:, 6:9])
                           
        eps_N_p_Emn, sigma_N_Emn = copy.deepcopy(self.get_normal_law(
            e_N_arr, eps_N_p_Emn_aux, eps_N_aux))

        eps_T_pi_Emna, sigma_T_Emna = copy.deepcopy(self.get_tangential_law(
            e_T_vct_arr, eps_T_pi_Emna_aux, eps_T_aux))

        delta = np.identity(3)
    
        sig_Emab = (
                np.einsum('n,...n,na,nb->...ab',
                          self._MPW, sigma_N_Emn, self._MPN, self._MPN) +
                0.5 * (
                        np.einsum('n,...nf,na,fb->...ab',
                                  self._MPW, sigma_T_Emna, self._MPN, delta) +
                        np.einsum('n,...nf,nb,fa->...ab', self._MPW,
                                  sigma_T_Emna, self._MPN, delta)
                )
        )

        return sig_Emab
    
    def get_corr_pred_EEQ(self, eps_Emab, int_var_accepted): 

        # Corrector predictor computation.

        e_N_arr = self._get_e_N_Emn(eps_Emab)
        e_T_vct_arr = self._get_e_T_Emnar(eps_Emab)
        
        eps_N_aux = copy.deepcopy(int_var_accepted[:, 1])
        eps_N_p_Emn_aux = copy.deepcopy(int_var_accepted[:, 0])
        eps_T_pi_Emna_aux = copy.deepcopy(int_var_accepted[:, 3:6])
        eps_T_aux = copy.deepcopy(int_var_accepted[:, 6:9])
                           
        eps_N_p_Emn, sigma_N_Emn = copy.deepcopy(self.get_normal_law(
            e_N_arr, eps_N_p_Emn_aux, eps_N_aux))

        eps_T_pi_Emna, sigma_T_Emna = copy.deepcopy(self.get_tangential_law(
            e_T_vct_arr, eps_T_pi_Emna_aux, eps_T_aux))

        delta = np.identity(3)
    
        D_Emabcd = self.elasticity_tensor
        
        eps_p_Emab = (
                    np.einsum('n,...n,na,nb->...ab',
                              self._MPW, eps_N_p_Emn, self._MPN, self._MPN) +
                    0.5 * (
                            np.einsum('n,...nf,na,fb->...ab',
                                      self._MPW, eps_T_pi_Emna, self._MPN, delta) +
                            np.einsum('n,...nf,nb,fa->...ab', self._MPW,
                                      eps_T_pi_Emna, self._MPN, delta)
                    )
            )
        
        eps_e_Emab = eps_Emab - eps_p_Emab
        
        sig_Emab = np.einsum('...abcd,...cd->...ab', D_Emabcd, eps_e_Emab)
        
        return sig_Emab

    # -----------------------------------------------
    # number of microplanes - currently fixed for 3D
    # -----------------------------------------------
    n_mp = tr.Constant(21)

    # -----------------------------------------------
    # get the normal vectors of the microplanes
    # -----------------------------------------------
    _MPN = tr.Property(depends_on='n_mp')

    @tr.cached_property
    def _get__MPN(self):
        return np.array([[1,0,0],
                        [0,1,0],
                        [0,0,1],
                        [0.707106781187,0.707106781187,0],
                        [0.707106781187,-0.707106781187,0],
                        [0.707106781187,0,0.707106781187],
                        [0.707106781187,0,-0.707106781187],
                        [0,0.707106781187,0.707106781187],
                        [0,0.707106781187,-0.707106781187],
                        [0.387907304067,0.387907304067,0.836095596749],
                        [0.387907304067,0.387907304067,-0.836095596749],
                        [0.387907304067,-0.387907304067,0.836095596749],
                        [0.387907304067,-0.387907304067,-0.836095596749],
                        [0.387907304067,0.836095596749,0.387907304067],
                        [0.387907304067,0.836095596749,-0.387907304067],
                        [0.387907304067,-0.836095596749,0.387907304067],
                        [0.387907304067,-0.836095596749,-0.387907304067],
                        [0.836095596749,0.387907304067,0.387907304067],
                        [0.836095596749,0.387907304067,-0.387907304067],
                        [0.836095596749,-0.387907304067,0.387907304067],
                        [0.836095596749,-0.387907304067,-0.387907304067]
                        ])

  

    # -------------------------------------
    # get the weights of the microplanes
    # -------------------------------------
    _MPW = tr.Property(depends_on='n_mp')

    @tr.cached_property
    def _get__MPW(self):
        return np.array([0.0265214244093,
                        0.0265214244093,
                        0.0265214244093,
                        0.0199301476312,
                        0.0199301476312,
                        0.0199301476312,
                        0.0199301476312,
                        0.0199301476312,
                        0.0199301476312,
                        0.0250712367487,
                        0.0250712367487,
                        0.0250712367487,
                        0.0250712367487,
                        0.0250712367487,
                        0.0250712367487,
                        0.0250712367487,
                        0.0250712367487,
                        0.0250712367487,
                        0.0250712367487,
                        0.0250712367487,
                        0.0250712367487
                        ])*6.0
    
    elasticity_tensor = Property(
        depends_on='E, nu, dimensionality')
    
    @cached_property
    def _get_elasticity_tensor(self):

        # ----------------------------------------------------------------------------
        # Lame constants calculated from E and nu
        # ----------------------------------------------------------------------------
        # first Lame paramter
        la = self.E * self.nu / ((1 + self.nu) * (1 - 2 * self.nu))
        # second Lame parameter (shear modulus)
        mu = self.E / (2 + 2 * self.nu)

        # -----------------------------------------------------------------------------------------------------
        # Get the fourth order elasticity and compliance tensors for the 2D-case
        # -----------------------------------------------------------------------------------------------------

        # construct the elasticity tensor (using Numpy - einsum function)
        delta = np.identity(3)
        D_ijkl = (np.einsum(',ij,kl->ijkl', la, delta, delta) +
                  np.einsum(',ik,jl->ijkl', mu, delta, delta) +
                  np.einsum(',il,jk->ijkl', mu, delta, delta))

        return D_ijkl


In [30]:
class MATH3DMic():
    
    DELTA = np.identity(3)
    EPS = np.zeros((3, 3, 3), dtype='f')
    EPS[(0, 1, 2), (1, 2, 0), (2, 0, 1)] = 1
    EPS[(2, 1, 0), (1, 0, 2), (0, 2, 1)] = -1

    DD = np.hstack([DELTA, np.zeros_like(DELTA)])
    EEPS = np.hstack([np.zeros_like(EPS), EPS])

    GAMMA = np.einsum(
        'ik,jk->kij', DD, DD
    ) + np.einsum(
        'ikj->kij', np.fabs(EEPS)
    )

    def get_eps_ab(eps_O): return np.einsum(
        'Oab,...O->...ab', GAMMA, eps_O
    )[np.newaxis, ...]

    GAMMA_inv = np.einsum(
        'aO,bO->Oab', DD, DD
    ) + 0.5 * np.einsum(
        'aOb->Oab', np.fabs(EEPS)
    )


    def get_sig_O(sig_ab): return np.einsum(
        'Oab,...ab->...O', GAMMA_inv, sig_ab
    )[0, ...]


    GG = np.einsum(
        'Oab,Pcd->OPabcd', GAMMA_inv, GAMMA_inv
    )


    def get_K_OP(D_abcd):
        return np.einsum(
            'OPabcd,abcd->OP', GG, D_abcd
        )

    
    def get_state_var(int_var):  # unpacks saved data

        eps_N_p_Emn = copy.deepcopy(int_var[..., 0])
        eps_N_Emn = copy.deepcopy(int_var[..., 1])
        sigma_N_Emn = copy.deepcopy(int_var[..., 2])

        eps_T_pi_Emna = copy.deepcopy(int_var[..., 3:6])
        eps_T_Emna = copy.deepcopy(int_var[..., 6:9])
        sigma_T_Emna = copy.deepcopy(int_var[..., 9:12])

        return eps_N_p_Emn, eps_N_Emn, sigma_N_Emn, eps_T_pi_Emna, eps_T_Emna, sigma_T_Emna
                               
    def get_dot_state_var(int_var, int_var_accepted):  

        eps_N_p_Emn_dot = copy.deepcopy(int_var[:, 0] - int_var_accepted[:, 0])
        eps_N_Emn_dot = copy.deepcopy(int_var[:, 1]) - copy.deepcopy(int_var_accepted[:, 1])
        sigma_N_Emn_dot = copy.deepcopy(int_var[:, 2]) - copy.deepcopy(int_var_accepted[:, 2])

        eps_T_pi_Emna_dot = copy.deepcopy(int_var[:, 3:6]) - copy.deepcopy(int_var_accepted[:, 3:6])
        eps_T_Emna_dot = copy.deepcopy(int_var[:, 6:9]) - copy.deepcopy(int_var_accepted[:, 6:9])
        sigma_T_Emna_dot = copy.deepcopy(int_var[:, 9:12]) - copy.deepcopy(int_var_accepted[:, 9:12])

        return eps_N_p_Emn_dot, eps_N_Emn_dot, sigma_N_Emn_dot, eps_T_pi_Emna_dot, eps_T_Emna_dot, sigma_T_Emna_dot
    
    def get_energy(eps_ab_list, sig_ab_list, state_var):
        
        energy = np.zeros((len(state_var),4))
        
        MPN = np.array([[1,0,0],
                        [0,1,0],
                        [0,0,1],
                        [0.707106781187,0.707106781187,0],
                        [0.707106781187,-0.707106781187,0],
                        [0.707106781187,0,0.707106781187],
                        [0.707106781187,0,-0.707106781187],
                        [0,0.707106781187,0.707106781187],
                        [0,0.707106781187,-0.707106781187],
                        [0.387907304067,0.387907304067,0.836095596749],
                        [0.387907304067,0.387907304067,-0.836095596749],
                        [0.387907304067,-0.387907304067,0.836095596749],
                        [0.387907304067,-0.387907304067,-0.836095596749],
                        [0.387907304067,0.836095596749,0.387907304067],
                        [0.387907304067,0.836095596749,-0.387907304067],
                        [0.387907304067,-0.836095596749,0.387907304067],
                        [0.387907304067,-0.836095596749,-0.387907304067],
                        [0.836095596749,0.387907304067,0.387907304067],
                        [0.836095596749,0.387907304067,-0.387907304067],
                        [0.836095596749,-0.387907304067,0.387907304067],
                        [0.836095596749,-0.387907304067,-0.387907304067]
                        ])
        
        MPW = np.array([0.0265214244093,
                        0.0265214244093,
                        0.0265214244093,
                        0.0199301476312,
                        0.0199301476312,
                        0.0199301476312,
                        0.0199301476312,
                        0.0199301476312,
                        0.0199301476312,
                        0.0250712367487,
                        0.0250712367487,
                        0.0250712367487,
                        0.0250712367487,
                        0.0250712367487,
                        0.0250712367487,
                        0.0250712367487,
                        0.0250712367487,
                        0.0250712367487,
                        0.0250712367487,
                        0.0250712367487,
                        0.0250712367487
                        ]) * 6.0
        
        for i in range(1,len(state_var)): 
            
            eps_N_p_Emn, eps_N_Emn, sigma_N_Emn, eps_T_pi_Emna, eps_T_Emna, sigma_T_Emna =\
            copy.deepcopy(MATH3DMic.get_state_var(state_var[i]))

            eps_N_p_Emn_aux, eps_N_Emn_aux, sigma_N_Emn_aux, eps_T_pi_Emna_aux, eps_T_Emna_aux, sigma_T_Emna_aux =\
            copy.deepcopy(MATH3DMic.get_state_var(state_var[i-1]))

            eps_N_p_Emn_dot, eps_N_Emn_dot, sigma_N_Emn_dot, eps_T_pi_Emna_dot, eps_T_Emna_dot, sigma_T_Emna_dot =\
            copy.deepcopy(MATH3DMic.get_dot_state_var(state_var[i], state_var[i-1]))

            delta = np.identity(3)

            sig_ab = MATH3DMic.get_eps_ab(sig_ab_list[i])

            eps_ab = MATH3DMic.get_eps_ab(eps_ab_list[i])

            eps_ab_aux = MATH3DMic.get_eps_ab(eps_ab_list[i - 1])
            
            eps_p_Emab = (
                    np.einsum('n,...n,na,nb->...ab',
                              MPW, eps_N_p_Emn, MPN, MPN) +
                    0.5 * (
                            np.einsum('n,...nf,na,fb->...ab',
                                      MPW, eps_T_pi_Emna, MPN, delta) +
                            np.einsum('n,...nf,nb,fa->...ab', MPW,
                                      eps_T_pi_Emna, MPN, delta)
                    )
            )

            eps_p_Emab_aux = (
                    np.einsum('n,...n,na,nb->...ab',
                              MPW, eps_N_p_Emn_aux, MPN, MPN) +
                    0.5 * (
                            np.einsum('n,...nf,na,fb->...ab',
                                      MPW, eps_T_pi_Emna_aux, MPN, delta) +
                            np.einsum('n,...nf,nb,fa->...ab', MPW,
                                      eps_T_pi_Emna_aux, MPN, delta)
                    )
            )
            
            plast_work_N = np.einsum('...,...->...', sigma_N_Emn, eps_N_p_Emn_dot)
            
            plast_work_T = np.einsum('...n,...n->...', sigma_T_Emna, eps_T_pi_Emna_dot)

            plast_work_mic = np.einsum('...n,...n->...', MPW, plast_work_N) +  \
                                   np.einsum('...n,...n->...', MPW, plast_work_T)

            #plast_diss = np.einsum('...n,...n->...', MPW, (plast_dissip_N + plast_dissip_T)) 

            energy[i , 0] = plast_work_mic

            work_micro_N = np.einsum('...n,...n->...n', sigma_N_Emn, eps_N_Emn_dot)
            
            work_micro_T = np.einsum('...ij,...ij->...i', sigma_T_Emna, eps_T_Emna_dot)
            
            work_micro = np.einsum('...n,...n->...', MPW, work_micro_N) + \
                                    np.einsum('...n,...n->...', MPW, work_micro_T)

            energy[i , 1] = work_micro

            plast_diss_macro = np.einsum('...ij,...ij->...', sig_ab, eps_p_Emab - eps_p_Emab_aux)

            energy[i , 2] = plast_diss_macro

            work_macro = np.einsum('...ij,...ij->...', sig_ab, eps_ab - eps_ab_aux)

            energy[i , 3] = work_macro

        return energy
        

In [24]:
n = 100
s_levels = np.linspace(0, 0.005, 2)
s_levels[0] = 0
s_levels.reshape(-1, 2)[:, 0] *= 0
#s_levels.reshape(-1, 2)[:, 1] *= -1
s_history = s_levels.flatten()
s_arr = np.hstack([np.linspace(s_history[i], s_history[i + 1], n)
                for i in range(len(s_levels) - 1)])

# Tension-Compression
eps = np.array([np.array([[-s_arr[i], 0, 0],
                    [0, 0, 0],
                    [0, 0, 0]]) for i in range(0, len(s_arr))])


# # Shear
# eps = array([array([[0, s_arr[i], 0],
#                     [s_arr[i], 0, 0],
#                     [0, 0, 0]]) for i in range(0, len(s_arr))])

mats = MATS3DMplNTSimp()


# Paramters

n_mp = mats.n_mp

sigma_EEQ = np.zeros_like(eps)
sigma_PVW = np.zeros((3,3))

state_var_PVW = np.zeros((n_mp, 12))
state_var_accepted_PVW = np.zeros((n_mp, 12))
state_var_EEQ = np.zeros((n_mp, 12))
state_var_accepted_EEQ = np.zeros((n_mp, 12))
U_t_list, F_t_list, energy_list, state_var_list = [], [], [], []

for i in range(0, len(eps[:, 0, 0])):
    
    sigma_PVW = copy.deepcopy(mats.get_corr_pred_PVW(
                eps[i, :], state_var_PVW))


    state_var_PVW = copy.deepcopy(mats._x_get_state_variables(eps[i, :], state_var_PVW, state_var_accepted_PVW))

#         energy = MATH3DMic.get_energy(state_var, state_var_accepted, sig_ab, eps_ab, eps_aux, eps_p_Emab, eps_p_Emab_aux)

    state_var_accepted_PVW = copy.deepcopy(state_var_PVW)
    
    U_k_O = MATH3DMic.get_sig_O(eps[i, :].reshape(1, 3, 3)).reshape(6, )
    F_O = MATH3DMic.get_sig_O(sigma_PVW.reshape(1, 3, 3)).reshape(6, )

    U_t_list.append(np.copy(U_k_O))
    F_t_list.append(copy.deepcopy(F_O))
    state_var_list.append(copy.deepcopy(state_var_accepted_PVW))

U_t_PVW, F_t_PVW, state_var_PVW = np.array(U_t_list), np.array(F_t_list), np.array(state_var_list)

eps_N_p_Emn_PVW, eps_N_Emn_PVW, sigma_N_Emn_PVW, eps_T_pi_Emna_PVW, eps_T_Emna_PVW, sigma_T_Emna_PVW = \
MATH3DMic.get_state_var(state_var_PVW)
                                                
energy_PVW = MATH3DMic.get_energy(U_t_PVW, F_t_PVW, state_var_PVW)

U_t_list, F_t_list, energy_list, state_var_list = [], [], [], []

s_levels = np.linspace(0, 0.005, 2)
s_levels[0] = 0
s_levels.reshape(-1, 2)[:, 0] *= 0
#s_levels.reshape(-1, 2)[:, 1] *= -1
s_history = s_levels.flatten()
s_arr = np.hstack([np.linspace(s_history[i], s_history[i + 1], n)
                for i in range(len(s_levels) - 1)])

# Tension-Compression
eps = np.array([np.array([[-s_arr[i], 0, 0],
                    [0, 0, 0],
                    [0, 0, 0]]) for i in range(0, len(s_arr))])

for i in range(0, len(eps[:, 0, 0])):
    
    sigma_EEQ = copy.deepcopy(mats.get_corr_pred_EEQ(
                eps[i, :], state_var_EEQ))


    state_var_EEQ = copy.deepcopy(mats._x_get_state_variables(eps[i, :], state_var_EEQ, state_var_accepted_EEQ))

#         energy = MATH3DMic.get_energy(state_var, state_var_accepted, sig_ab, eps_ab, eps_aux, eps_p_Emab, eps_p_Emab_aux)

    state_var_accepted_EEQ = copy.deepcopy(state_var_EEQ)
    
    U_k_O = MATH3DMic.get_sig_O(eps[i, :].reshape(1, 3, 3)).reshape(6, )
    F_O = MATH3DMic.get_sig_O(sigma_EEQ.reshape(1, 3, 3)).reshape(6, )

    U_t_list.append(np.copy(U_k_O))
    F_t_list.append(copy.deepcopy(F_O))
    state_var_list.append(copy.deepcopy(state_var_accepted_EEQ))

U_t_EEQ, F_t_EEQ, state_var_EEQ = np.array(U_t_list), np.array(F_t_list), np.array(state_var_list)

eps_N_p_Emn_EEQ, eps_N_Emn_EEQ, sigma_N_Emn_EEQ, eps_T_pi_Emna_EEQ, eps_T_Emna_EEQ, sigma_T_Emna_EEQ = \
MATH3DMic.get_state_var(state_var_EEQ)
                                                
energy_EEQ = MATH3DMic.get_energy(U_t_EEQ, F_t_EEQ, state_var_EEQ)



[[[-1.9640853   0.          0.        ]
  [ 0.         -0.49102132  0.        ]
  [ 0.          0.         -0.49102132]]]
[[[-3.45935754  0.          0.        ]
  [ 0.         -0.98204265  0.        ]
  [ 0.          0.         -0.98204265]]]
[[[-4.08834168  0.          0.        ]
  [ 0.         -1.28659508  0.        ]
  [ 0.          0.         -1.28659508]]]
[[[-4.36502523  0.          0.        ]
  [ 0.         -1.41499722  0.        ]
  [ 0.          0.         -1.41499722]]]
[[[-4.64170878  0.          0.        ]
  [ 0.         -1.54339936  0.        ]
  [ 0.          0.         -1.54339936]]]
[[[-4.91839233  0.          0.        ]
  [ 0.         -1.67180149  0.        ]
  [ 0.          0.         -1.67180149]]]
[[[-5.19507588  0.          0.        ]
  [ 0.         -1.80020363  0.        ]
  [ 0.          0.         -1.80020363]]]
[[[-5.47175943  0.          0.        ]
  [ 0.         -1.92860577  0.        ]
  [ 0.          0.         -1.92860577]]]
[[[-5.74844298  0.      

In [29]:
%matplotlib widget

import matplotlib.pyplot as plt
fig, ((ax_1, ax_2), (ax_3, ax_4)) = plt.subplots(2,2, tight_layout=True, figsize=(9,8))
# fig.canvas.header_visible=False

# t = np.linspace(0, 1, len(U_t_PVW[:, 0]))

ax_1.plot(U_t_PVW[:, 0], F_t_PVW[:, 0])
ax_1.set_xlabel('$\epsilon_{11}$')
ax_1.set_ylabel('$\sigma_{11}$')
ax_1.set_title('$\sigma_{11} - \epsilon_{11} \; PVW$')    


ax_2.plot(U_t_PVW[:, 0], energy_PVW[:, 0], linewidth=1, label='plastic micro')
ax_2.plot(U_t_PVW[:, 0], energy_PVW[:, 1], linewidth=2, label='work micro')
ax_2.plot(U_t_PVW[:, 0], energy_PVW[:, 2], linewidth=1, label='plastic macro')
ax_2.plot(U_t_PVW[:, 0], energy_PVW[:, 3], linewidth=1, label='work macro')
ax_2.set_xlabel('$\epsilon_{11}$')
ax_2.set_ylabel('$J/cm^3$')
ax_2.set_title('$Energy \; evaluation \; PVW$')
# handles, labels = ax_2.get_legend_handles_labels()
ax_2.legend(handles, labels)

ax_3.plot(U_t_EEQ[:, 0], F_t_EEQ[:, 0])
# ax_3.plot(U_t_PVW[:, 0], F_t_PVW[:, 0])
ax_3.set_xlabel('$\epsilon_{11}$')
ax_3.set_ylabel('$\sigma_{11}$')
ax_3.set_title('$\sigma_{11} - \epsilon_{11} \; EEQ$')    


ax_4.plot(U_t_EEQ[:, 0], energy_EEQ[:, 0], linewidth=1, label='plastic micro')
ax_4.plot(U_t_EEQ[:, 0], energy_EEQ[:, 1], linewidth=2, label='work micro')
ax_4.plot(U_t_EEQ[:, 0], energy_EEQ[:, 2], linewidth=1, label='plastic macro')
ax_4.plot(U_t_EEQ[:, 0], energy_EEQ[:, 3], linewidth=1, label='work macro')
ax_4.set_xlabel('$\epsilon_{11}$')
ax_4.set_ylabel('$J/cm^3$')
ax_4.set_title('$Energy \; evaluation \; EEQ$')
ax_4.legend(handles, labels)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …