In [1]:
%matplotlib widget
from bmcs_matmod.slide.vslide_34 import Slide34
from bmcs_matmod.slide.slide_explorer import SlideExplorer
import bmcs_matmod.slide.vslide_34 as slide_34
import numpy as np
from mayavi import mlab
from bmcs_matmod.slide.f_double_cap import FDoubleCap
import matplotlib.pylab as plt

# Test the return mapping for a large step beyond elastic limit

Return mapping includes also the evaluation of damage due to sliding and opening. Even though the threshold function is linear in the normal direction to the yield locus in stress space, it is nonlinear with respect to the other stress variables, i.e. $Y_\mathrm{N}, Y_\mathrm{T}$. Therefore, several iterations are required during when the step induces a high amount of damage. Following example demonstrates this for a relatively large step.
Would it make sense to visualize the threshold function in terms of f and lambda?

In [2]:
material_params = dict(
    E_T=1, gamma_T=0, K_T=0, S_T=10000, c_T=1, bartau=1,
    E_N=1, S_N=10000, c_N = 1, m = 0.1, f_t=1, f_c=20, f_c0=10, eta=0
)

In [3]:
se = SlideExplorer(n_steps=40, k_max=50)
se.slide_model.trait_set(**material_params);
se.slide_model.f_lambda_recording=True # show the iteration

In [4]:
se.trait_set(s_x_1 = 4, s_y_1 = 0, w_1 = -20);
se.run()
# se.trait_set(s_x_1 = 2, s_y_1 = 0, w_1 = 1);
# se.run()
se.interact()

In [5]:
fig, ax = plt.subplots(1,1)
se.slide_model.lam_max = 0.8
lam_lines = np.array(se.slide_model.lam_list)
f_lines = np.array(se.slide_model.f_list)
ax.plot(lam_lines.T, f_lines.T)
ax.plot([lam_lines.T[0],lam_lines.T[-1]],[0,0], color='black', lw=0.2);

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [6]:
s = Slide34(**material_params, k_max=50)
fdc = FDoubleCap(tau_bar=1,**material_params)

In [7]:
delta_f = 2 * s.f_t
min_sig = -s.f_c - delta_f
max_sig = s.f_t + delta_f
max_tau = s.bartau + s.m * s.f_c0 + delta_f
min_tau = -max_tau

In [19]:
min_w = min_sig / s.E_N
max_w = max_sig / s.E_N
min_s = min_tau / s.E_T
max_s = max_tau / s.E_T
s_range = np.linspace(min_s, max_s, 2)
w_range = np.linspace(min_w, max_w, 2)
s_grid, w_grid  = np.meshgrid(s_range,w_range)
s_x_n1 = np.hstack([s_grid[:,(0,-1)].flatten(), s_grid[(0,-1),1:-1].flatten()])
s_y_n1 = np.zeros_like(s_x_n1)
w_n1 = np.hstack([w_grid[:,(0,-1)].flatten(), w_grid[(0,-1),1:-1].flatten()])
s_x_n1, w_n1

(array([-4.,  4., -4.,  4.]), array([-22., -22.,   3.,   3.]))

In [9]:
discr_shape = (len(w_n1),)
#discr_shape = (2,)

state = {
    var_name: np.zeros(discr_shape + var_shape, dtype=np.float_)
    for var_name, var_shape in
    s.state_var_shapes.items()
}

In [10]:
eps_Ema = np.c_[s_x_n1, s_y_n1, w_n1] 
eps_Ema

array([[ -4.        ,   0.        , -22.        ],
       [  4.        ,   0.        , -22.        ],
       [ -4.        ,   0.        , -13.66666667],
       [  4.        ,   0.        , -13.66666667],
       [ -4.        ,   0.        ,  -5.33333333],
       [  4.        ,   0.        ,  -5.33333333],
       [ -4.        ,   0.        ,   3.        ],
       [  4.        ,   0.        ,   3.        ],
       [ -1.33333333,   0.        , -22.        ],
       [  1.33333333,   0.        , -22.        ],
       [ -1.33333333,   0.        ,   3.        ],
       [  1.33333333,   0.        ,   3.        ]])

In [35]:
slide = Slide34(**material_params)
discr_shape = (1,)
state = {
    var_name: np.zeros(discr_shape + var_shape, dtype=np.float_)
    for var_name, var_shape in
    slide.state_var_shapes.items()
}

In [ ]:
slide.get_

In [11]:
se2 = SlideExplorer(n_steps=40, k_max=50)
se2.slide_model.trait_set(**material_params);

In [20]:
se2.Eps_n1
s_x_n1

array([-4.,  4., -4.,  4.])

In [29]:
se2.slide_model.get_f_df(s_x_n1[0], s_y_n1[0], w_n1[0], 
                         se2.Eps_n1, se2.Sig_n1 )

(array([2.86101751]),
 array([[-0.80317829]]),
 array([ -4.,  -0., -22.,   0.,   0.,   0.,   8.,   0.]))

In [30]:
se2.Eps_n1.shape

(8,)

In [31]:
# eps_Ema = np.zeros(discr_shape+(3,), dtype=np.float_) + 1e-9
# eps_Ema[0,0] = 1.1
# eps_Ema[0,2] = 0.4
# s.k_max = 3
# sig_Ema, D_Emab = s.get_corr_pred(eps_Ema, 1, **state)
# sig_Ema

# Plot the yield surface in 2D

In [32]:
%matplotlib widget
from bmcs_matmod.slide.vslide_34 import Slide34
from bmcs_matmod.slide.slide_explorer import SlideExplorer
import bmcs_matmod.slide.vslide_34 as slide_34
import numpy as np
from mayavi import mlab
from bmcs_matmod.slide.f_double_cap import FDoubleCap
import matplotlib.pylab as plt

In [33]:
material_params = dict(
    E_T=1, gamma_T=0, K_T=0, S_T=10000, c_T=1, bartau=1,
    E_N=1, S_N=10000, c_N = 1, m = 0.1, f_t=1, f_c=20, f_c0=10, eta=0
)

In [14]:
fdc = FDoubleCap(tau_bar=1,**material_params)
min_sig, max_sig = -30, 10
min_tau, max_tau = -10,10

In [15]:
X_a, Y_a = np.mgrid[min_sig:max_sig:210j, min_tau:max_tau:210j]
Z_a = fdc.symb.get_f_solved(X_a, Y_a)
Z_0 = np.zeros_like(Z_a)

In [16]:
mlab.init_notebook('ipy')

Notebook initialized with ipy backend.


In [17]:
mlab.clf()
mlab.figure(bgcolor=(1,1,1))
mlab.surf(X_a, Y_a, Z_a, colormap='cool')
mlab.surf(X_a, Y_a, Z_0, color=(.8,.8,.8))

Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x01\x90\x00\x00\x01^\x08\x02\x00\x00\x00$?\xde_\x00\…

In [18]:
mlab.show()

# Plot the yield surface in 3D

In [19]:
%matplotlib widget
from bmcs_matmod.slide.vslide_34 import Slide34
from bmcs_matmod.slide.slide_explorer import SlideExplorer
import bmcs_matmod.slide.vslide_34 as slide_34
import numpy as np
from mayavi import mlab
from bmcs_matmod.slide.f_double_cap import FDoubleCap
import matplotlib.pylab as plt

In [20]:
material_params = dict(
    E_T=1, gamma_T=0, K_T=0, S_T=10000, c_T=1, bartau=3,
    E_N=1, S_N=10000, c_N = 1, m = 0.2, f_t=1, f_c=5, f_c0=4, eta=0
)
fdc = FDoubleCap(tau_bar=1,**material_params)

In [21]:
min_sig, max_sig = -12, 5
min_tau, max_tau = -8,8
X1_a, Y1_a, Z1_a = np.mgrid[min_sig:max_sig:210j, 0:max_tau:210j, min_tau:max_tau:210j]
YZ1_a = np.sqrt(Y1_a**2 + Z1_a**2)
f1_a = fdc.symb.get_f_solved(X1_a, YZ1_a)

In [22]:
X2_a, Y2_a, Z2_a = np.mgrid[min_sig:max_sig:210j, min_tau:max_tau:210j, min_tau:max_tau:210j]
YZ2_a = np.sqrt(Y2_a**2 + Z2_a**2)
f2_a = fdc.symb.get_f_solved(X2_a, YZ2_a)

In [23]:
mlab.options.backend = 'envisage'
mlab.figure(bgcolor=(1,1,1))
mlab.contour3d(X1_a, Y1_a, Z1_a, f1_a, contours=[0], opacity=1)
mlab.contour3d(X2_a, Y2_a, Z2_a, f2_a, contours=[0], opacity=0.3)
mlab.show()